# Generated by Django 5.0.7 on 2024-07-16 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barcode_generator', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Custom User', 'verbose_name_plural': 'Custom Users'},
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='custom_user',
        ),
    ]
