# Generated by Django 5.0.7 on 2024-07-17 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcode_generator', '0002_alter_customuser_options_alter_customuser_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcode',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='barcodes/'),
        ),
    ]
