# Generated by Django 5.0.7 on 2024-07-17 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcode_generator', '0003_alter_barcode_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcode',
            name='image',
            field=models.ImageField(default='default_image.png', upload_to='barcodes/'),
        ),
    ]
