# Generated by Django 5.0.7 on 2024-07-17 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcode_generator', '0004_alter_barcode_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barcode',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='barcode',
            name='barcode_number',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='barcode',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='barcodes/'),
        ),
    ]
