# Generated by Django 5.0.7 on 2024-07-17 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barcode_generator', '0006_generatedbarcodefolder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeneratedBarcodeFolder',
        ),
    ]
