# Generated by Django 5.0.7 on 2024-07-18 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcode_generator', '0007_delete_generatedbarcodefolder'),
    ]

    operations = [
        migrations.AddField(
            model_name='barcode',
            name='folder_name',
            field=models.CharField(default='default_folder_name', max_length=100),
        ),
    ]
