# Generated by Django 5.0.7 on 2024-07-22 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcode_generator', '0008_barcode_folder_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
